### ISSUE TITLE
Run integration tests during CI builds

### ISSUE THREAD

**Issue by C0urante** [aiven/jdbc-connector-for-apache-kafka#221]
We don't run integration tests during our CI builds. This makes the tests susceptible to atrophy during, e.g., automated dependency bumping, and reduces their value since they have to be run locally and, if forgotten, bugs and other undesirable changes may slip through. It'd be nice if we could start running integration tests for every PR and/or new commit to the main branch.

**Comment by jeqo** [comment]
Fixed by #224
